YAASApp/urls.py
from django.urls import path

from YAASApp.api_rest import api_auction_list, api_auction_by_id, api_auction_by_title, api_bid_auction
from . import views

app_name = 'YAASApp'
urlpatterns = (
    path('language/<slug:lang_code>', views.change_language, name='language'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.EditUserView.as_view(), name='userdetail'),
    path('createauction/', views.create_auction, name='createauction'),
    path('saveauction/', views.save_auction, name='saveauction'),
    path('', views.AuctionIndex.as_view(), name='auctionindex'),
    path('auctionbyname/', views.AuctionSearch.as_view(), name='auction_by_name'),
    path('detail/<int:pk>/', views.AuctionDetail.as_view(), name='auctiondetail'),
    path('auctionuser/', views.AuctionUser.as_view(), name='auctionuser'),
    path('editauction/<int:id>', views.EditUserAuction.as_view(), name='edit_user_auction'),
    path('bidauction/<int:auction_id>', views.bid_auction, name='bid_auction'),

    path('banauctions/', views.BanAuctions.as_view(), name='list_ban_auction'),
    path('banauctions/<int:auction_id>', views.ban_auction, name='ban_auction'),
    path('emails/', views.email_history, name='emails'),

    path('api/auctions/', api_auction_list),
    path('api/auctions/<int:auction_id>', api_auction_by_id),
    path('api/auctionsbytitle/', api_auction_by_title),
    path('api/bid/', api_bid_auction),

    path('generatedata/', views.data_generation, name="data_generation"),
)

YAASThomasGAY/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('YAASApp/', include('YAASApp.urls')),
    path('admin/', admin.site.urls)
]

YAASApp/models.py
import datetime
from django.contrib.auth.models import User

from django.db import models


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    preferred_language = models.CharField(max_length=2, choices=(('en', 'English'), ('fr', 'Francais')), default='en')

    def __str__(self):
        return self.user.__str__() + self.preferred_language


class Auction(models.Model):
    title = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)
    minimum_price = models.DecimalField(max_digits=11, decimal_places=2)
    current_price = models.DecimalField(max_digits=11, decimal_places=2)
    deadline = models.DateTimeField(default=datetime.datetime.today()+datetime.timedelta(minutes=1)) #TODO : timedelta(days=3)
    status = models.CharField(max_length=2,
                              choices=(('AC', 'Active'), ('BA', 'Banned'), ('DU', 'DUE'), ('AD', 'Adjudicated')),
                              default='AC')
    seller = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1, related_name='seller')
    last_bidder = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='last_bidder', null=True)


class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='bidder', null=False)
    auction = models.ForeignKey(Auction, on_delete=models.DO_NOTHING, related_name='auction', null=False)
    bid_price = models.DecimalField(max_digits=11, decimal_places=2)

YAASApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from YAASApp.models import Profile, Auction, Bid


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')


class ProfileForm(ModelForm):
    preferred_language = forms.ChoiceField(choices=(('en', 'English'), ('fr', 'Francais')))

    class Meta:
        model = Profile
        fields = ('preferred_language',)


class AuctionForm(ModelForm):
    title = forms.CharField(required=True)
    deadline = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M:%S'], required=False,
                                   help_text='Format dd/mm/YYYY HH:MM:SS')

    class Meta:
        model = Auction
        fields = ('title', 'description', 'minimum_price', 'deadline')


class ConfAuctionForm(forms.Form):
    CHOICES = [(x, x) for x in ("Yes", "No")]
    option = forms.ChoiceField(choices=CHOICES)
    b_title = forms.CharField(widget=forms.HiddenInput())
    b_description = forms.CharField(widget=forms.HiddenInput())
    b_minimum_price = forms.FloatField(widget=forms.HiddenInput())
    b_deadline = forms.DateTimeField(widget=forms.HiddenInput())

class BidForm(ModelForm):
    class Meta:
        model = Bid
        fields = ('bid_price',)

YAASApp/views.py
import datetime
import os
from decimal import Decimal

from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from django.urls import reverse
from django.utils import translation, timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views import generic, View
from django.utils.translation import ugettext as _
from YAASApp.forms import ProfileForm, UserForm, AuctionForm, ConfAuctionForm
from YAASApp.models import Auction, Bid, Profile

# Register a new user
from YAASApp.utils import util_send_mail
from YAASThomasGAY.settings import EMAIL_FILE_PATH, TIME_ZONE


def change_language(request, lang_code):
    translation.activate(lang_code)
    request.session[translation.LANGUAGE_SESSION_KEY] = lang_code
    messages.add_message(request, messages.INFO, "language change to" + lang_code)

    if request.user.is_authenticated:
        user = request.user
        user.profile.preferred_language = lang_code
        user.profile.save()
    return HttpResponseRedirect(reverse("YAASApp:auctionindex"))


def register(request):
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = ProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            return redirect('YAASApp:auctionindex')

    else:
        user_form = UserForm(data=request.POST)
        profile_form = ProfileForm(data=request.POST)
    return render(request, 'YAASApp/register.html', {'user_form': user_form, 'profile_form': profile_form})


@csrf_exempt
def user_login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(request, username=username, password=password)

    if user is not None and user.is_superuser is False:
        login(request, user)
        return HttpResponseRedirect(reverse('YAASApp:language', args=(user.profile.preferred_language,)))
    if user is not None and user.is_superuser:
        login(request, user)
        return HttpResponseRedirect(reverse('YAASApp:auctionindex'))

    return render_to_response('YAASApp/login.html', )


@login_required
def user_logout(request):
    logout(request)
    return redirect('YAASApp:auctionindex')


class EditUserView(View):
    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'YAASApp/profile.html')

    @method_decorator(login_required)
    def post(self, request):
        u = request.user

        if request.POST["new_email"] != u.email:
            u.email = request.POST["new_email"]
            u.save()

        if request.POST["new_password"] != '':
            u.set_password(request.POST["new_password"])
            u.save()
            update_session_auth_hash(request, u)

        # Always redirect after a successful POST request
        return HttpResponseRedirect(reverse('YAASApp:userdetail'))


@login_required
def create_auction(request):
    if request.method == 'POST':
        auction_form = AuctionForm(data=request.POST)

        if auction_form.is_valid():
            auction = auction_form.save(commit=False)

            if auction.deadline < datetime.datetime.now(auction.deadline.tzinfo):# + datetime.timedelta(days=3):
                messages.warning(request, "Deadline is not valid")
                return render(request, 'YAASApp/createauction.html', {'auction_form': auction_form})

            cd = auction_form.cleaned_data
            b_title = cd['title']
            b_description = cd['description']
            b_minimum_price = cd['minimum_price']
            b_deadline = cd['deadline']
            conf_form = ConfAuctionForm({'b_title': b_title,
                                         'b_description': b_description,
                                         'b_minimum_price': b_minimum_price,
                                         'b_deadline': b_deadline})
            return render(request, 'YAASApp/auctionconf.html', {'conf_form': conf_form})

    auction_form = AuctionForm(data=request.POST)
    return render(request, 'YAASApp/createauction.html', {'auction_form': auction_form})


@login_required
def save_auction(request):
    option = request.POST['option']
    if option == 'Yes':
        title = request.POST['b_title']
        description = request.POST['b_description']
        m_p = request.POST['b_minimum_price']
        deadline = request.POST['b_deadline']
        auction = Auction(title=title, description=description,
                          minimum_price=m_p, deadline=deadline,
                          current_price=m_p, seller=request.user,
                          last_bidder=None)
        auction.save()
        util_send_mail('Auction creation', 'Your auction has successfully been created!', request.user.email)
        return HttpResponseRedirect(reverse('YAASApp:auctionuser'))
    else:
        return redirect('YAASApp:auctionindex')


class AuctionIndex(generic.ListView):
    template_name = 'YAASApp/home.html'
    context_object_name = 'auction_list'

    def get_queryset(self):
        return Auction.objects.filter(status='AC').order_by('deadline')


class AuctionSearch(generic.ListView):
    template_name = 'YAASApp/auctionbyname.html'
    context_object_name = 'auctions'

    @method_decorator(csrf_exempt)
    def get_queryset(self):
        intitle = self.request.GET['searchbox']
        return Auction.objects.filter(status='AC', title__icontains=intitle)


class AuctionDetail(generic.DetailView):
    model = Auction
    template_name = 'YAASApp/detailauction.html'


class AuctionUser(generic.ListView):
    template_name = 'YAASApp/userauctions.html'
    context_object_name = 'user_auctions'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AuctionUser, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Auction.objects.filter(seller=self.request.user, status='AC')


class EditUserAuction(View):
    @method_decorator(login_required)
    def get(self, request, id):
        auction = get_object_or_404(Auction, id=id)
        return render(request, 'YAASApp/editauction.html', {'auction': auction})

    @method_decorator(login_required)
    def post(self, request, id):
        auction = get_object_or_404(Auction, id=id)

        if request.POST['description'] != auction.description:
            auction.description = request.POST['description']
            auction.save()

        return HttpResponseRedirect(reverse('YAASApp:edit_user_auction', args=(auction.id,)))


@login_required
def bid_auction(request, auction_id):
    auction = get_object_or_404(Auction, pk=auction_id)
    if request.POST['bid_price'] != '':
        bid_price = Decimal(request.POST['bid_price'])

        if auction.seller != request.user and auction.current_price < bid_price and auction.last_bidder != request.user \
                and auction.status == 'AC':
            if auction.last_bidder is not None:
                util_send_mail('New bid on your auction', 'A new bid has been done on the auction you were wining ' +
                               auction.title, auction.last_bidder.email)
            auction.last_bidder = request.user
            auction.current_price = bid_price
            auction.save()
            bid = Bid(bidder=request.user, auction=auction, bid_price=bid_price)
            bid.save()
            util_send_mail('New bid on your auction', 'A new bid has been done on ' + auction.title,
                           auction.seller.email)
            messages.add_message(request, messages.INFO, _("Bid saved"))
            soft_deadline(auction=auction)
        else:
            messages.add_message(request, messages.ERROR, _("Bid is not conform (check the price)"))

    else:
        messages.add_message(request, messages.ERROR, _("Bid is not conform (check the price)"))

    return HttpResponseRedirect(reverse("YAASApp:auctiondetail", args=(auction_id,)))


def soft_deadline(auction):
    if auction.deadline - datetime.timedelta(minutes=5) < timezone.now() < auction.deadline:
        auction.deadline += datetime.timedelta(minutes=5)
        auction.save()


class BanAuctions(generic.ListView):
    template_name = 'YAASApp/banauctions.html'
    context_object_name = 'ban_auctions'

    @method_decorator(login_required)
    @method_decorator(staff_member_required)
    def dispatch(self, request, *args, **kwargs):
        return super(BanAuctions, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Auction.objects.filter(status='BA')


@login_required
@staff_member_required
def ban_auction(request, auction_id):
    auction = get_object_or_404(Auction, pk=auction_id)
    if auction.status == 'AC':
        auction.status = 'BA'
        auction.save()
        util_send_mail("Auction banned", "Your auction: " + auction.title + " has been banned", auction.seller.email)
        bids = Bid.objects.filter(auction=auction)
        for bid in bids:
            util_send_mail("Auction banned", "Auction: " + auction.title + " has been banned", bid.bidder.email)
        return HttpResponseRedirect(reverse('YAASApp:list_ban_auction'))


@login_required
@staff_member_required
def email_history(request):
    if request.user.is_superuser:
        directory = EMAIL_FILE_PATH
        emails = []
        for file in os.listdir(directory):

YAASApp/templates/YAASApp/auctionbyname.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Search results{% endblock %}

{% block content %}
<form method="get" action="{% url 'YAASApp:auction_by_name' %}">
     <input class="searchfield" id="searchbox" name="searchbox" type="text" value="{{ request.GET.searchbox }}" placeholder="Search..."/>
</form>

{% if auctions %}
    <ul>
    {% for auction in auctions %}
        <li>{{ auction.title }}
            <div><a href="{% url 'YAASApp:auctiondetail' auction.id %}">Detail</a> </div>
        </li>
    {% endfor %}
   </ul>
{% else %}
    <p>{% trans "No auctions available"%}</p>
{% endif %}
{% endblock %}

YAASApp/templates/YAASApp/auctionconf.html
{% extends 'base.html' %}

{% block title %}Confirm auction creation{% endblock %}
<h1>Confirm auction creation</h1>
{% block content %}
<form method="post" action="{% url 'YAASApp:saveauction' %}">
    {% csrf_token %}
    {{ conf_form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

YAASApp/templates/YAASApp/banauctions.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Ban auctions{% endblock %}

{% block content %}

{% if ban_auctions %}
    <ul>
    {% for auction in ban_auctions %}
        <li>{{ auction.title }}
            <div><strong>Description : </strong>{{ auction.description }}</div>
            <div><strong>{% trans "Seller" %} : </strong>{{ auction.seller }}</div>
        </li>
    {% endfor %}
   </ul>
{% else %}
    <p>{% trans "No auctions available"%}</p>
{% endif %}
{% endblock %}

YAASApp/templates/YAASApp/createauction.html
{% extends 'base.html' %}

{% block title %}Auction creation{% endblock %}
{% block content %}

{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
<form method="post">
    {% csrf_token %}
    {{ auction_form.as_p }}
<button type="submit">Create auction</button>
</form>
{% endblock %}

YAASApp/templates/YAASApp/detailauction.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Auction detail{% endblock %}

{% block content %}
    <h1>{{ auction.title }}</h1>

    <h3>Description</h3>
    <p>{{ auction.description }}</p>
    <p><strong>{% trans "Minimum Price" %} : </strong> {{ auction.minimum_price }}</p>
    <p><strong>{% trans "Current Price" %} : </strong> {{ auction.current_price }}</p>
    <p><strong>{% trans "Status" %} : </strong> {{ auction.status }}</p>
    <p><strong>{% trans "Deadline" %} : </strong> {{ auction.deadline }}</p>
    <p><strong>{% trans "Seller" %} : </strong>{{ auction.seller.username }}</p>


    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}

    {% if auction.seller != user and auction.last_bidder != user and user.is_authenticated %}
        <h3>{% trans "You can bid on this auction" %}</h3>
        <form method="post" action="{% url "YAASApp:bid_auction" auction.id %}">
            {% csrf_token %}
            Bid price: <input type="number" placeholder="10,0" id="bid_price" name="bid_price" step=".01">
            <br/>
            <button type="submit">Bid</button>
        </form>
    {% endif %}
    {% if user.is_superuser %}
        <h3>Ban this auction</h3>
        <form method="post" action="{% url "YAASApp:ban_auction" auction.id %}">
            {% csrf_token %}
            <button type="submit">Ban</button>
        </form>
    {% endif %}
{% endblock %}

YAASApp/templates/YAASApp/editauction.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
{% block title %}Auction detail{% endblock %}
    <h1>{{ auction.title }}</h1>

    <h3>Description</h3>
    <p>{{ auction.description }}</p>
    <p><strong>Minimum Price : </strong> {{ auction.minimum_price }}</p>
    <p><strong>Current Price : </strong> {{ auction.current_price }}</p>
    <p><strong>Status : </strong> {{ auction.status }}</p>
    <p><strong>Deadline : </strong> {{ auction.deadline }}</p>
    <p><strong>Seller :</strong>{{ auction.seller.username }}</p>
    <br/>

    <h2>Modify description</h2>
    New description : <textarea rows="7" cols="40" name="description" id="description" form="form_ea">{{ auction.description }}</textarea>
    <form method="post" id="form_ea">
        {% csrf_token %}
        <br>
        <!--New description : <input name="description" id="description" value="{{ auction.description }}"></input>-->
        <button type="submit">Save Changes</button>
    </form>
{% endblock %}

YAASApp/templates/YAASApp/emails.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h2>Emails history</h2>

    {% for email in emails %}
        <p>{{ email }}</p>
        <hr>
    {% endfor %}
{% endblock %}

YAASApp/templates/YAASApp/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Home{% endblock %}

{% block content %}
<form method="get" action="{% url 'YAASApp:auction_by_name' %}">
     <input class="searchfield" id="searchbox" name="searchbox" type="text" value="{{ request.GET.searchbox }}" placeholder="Search..."/>
</form>

{% if auction_list %}
    <ul>
    {% for auction in auction_list %}
        <li>{{ auction.title }}
            <div><a href="{% url 'YAASApp:auctiondetail' auction.id %}">Detail</a> </div>
        </li>
    {% endfor %}
   </ul>
{% else %}
    <p>{% blocktrans %}{{ "No auctions available" }}{% endblocktrans %}</p>
{% endif %}
{% endblock %}

YAASApp/templates/YAASApp/login.html
{% block title %}Login{% endblock %}
{% load i18n %}

{% block content %}
<h2>Login</h2>
  <form action="{% url 'YAASApp:login' %}" method="post">
      <div>{% trans "Username" %} : <input type="text" name="username" id="username"></div>
      <br/>
      <div>{% trans "Password" %} : <input type="password" name="password" id="password"></div>
    <button type="submit">{% trans "Login" %}</button>
  </form>
{% endblock %}

YAASApp/templates/YAASApp/profile.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Profile{% endblock %}

{% block content %}
<h2>Profile</h2>
    <p>
        <div>{% trans "Username" %} : {{ user.username }}</div>
        <div>{% trans "Email" %} : {{ user.email }}</div>
        <div>{% trans "First name" %} : {{ user.first_name }}</div>
        <div>{% trans "Last name" %} : {{ user.last_name }}</div>
    </p>

<form action="{% url 'YAASApp:userdetail' %}" method="post">
  {% csrf_token %}
      {% trans "New email" %} : <input type="text" name="new_email" id="new_email" value="{{ user.email }}">
      <br>
      {% trans "New Password" %} : <input type="password" name="new_password" id="new_password" value="">
      <br>
    <button type="submit">{% trans "Save Changes" %}</button>
  </form>
{% endblock %}

YAASApp/templates/YAASApp/register.html
{% block title %}register Page{% endblock %}
{% block body %}
<form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
<button type="submit">Register</button>
</form>
{% endblock %}

YAASApp/templates/YAASApp/userauctions.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Your auctions{% endblock %}

{% block content %}

{% if user_auctions %}
    <ul>
    {% for auction in user_auctions %}
        <li>{{ auction.title }}
            <div><a href="{% url 'YAASApp:edit_user_auction' auction.id %}">Detail/Edit</a> </div>
        </li>
    {% endfor %}
   </ul>
{% else %}
    <p>{% trans "No auctions available"%}</p>
{% endif %}
{% endblock %}